<?xml version ='1.0' encoding ='UTF-8' ?>
<definitions
	xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/'
	xmlns:xsd='http://www.w3.org/2001/XMLSchema'
	xmlns:soapenc='http://schemas.xmlsoap.org/soap/encoding/'
	xmlns:wsdl='http://schemas.xmlsoap.org/wsdl/'
	xmlns='http://schemas.xmlsoap.org/wsdl/'>
	<message name='predictFuture'>
		<part name='age'/>
		<part name='name'/>
	</message>
	<message name='predictFutureResponse'>
		<part name='Result'/>
	</message>
	<portType name='PFPortType'>
		<operation name='predictFuture'>
			<input message='tns:predictFutureRequest'/>
			<output message='tns:predictFutureResponse'/>
		</operation>
	</portType>
	<binding name='PFBinding' type='tns:PFPortType'>
		<soap:binding style='rpc'
			transport='http://schemas.xmlsoap.org/soap/http'/>
		<operation name='predictFuture'>
			<soap:operation soapAction='urn:predictFuture'/>
			<input>
				<soap:body use='literal' />
			</input>
			<output>
				<soap:body use='literal' />
			</output>
		</operation>
	</binding>
	<service name='PFService'>
		<port name='PFPort' binding='PFBinding'>
			<soap:address location='http://localhost/A5/C1/service.php'/>
		</port>
	</service>
</definitions>
